name: Auto-Docker functionality testing CI

on: [push]

jobs:
  validate_functions:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Check functions.py
        id: checkFunctions
        env:
          DEPLOY_BRANCH: ${{secrets.DEPLOY_BRANCH}}
          DOCKERHUB_ORG: ${{secrets.DOCKERHUB_ORG}}
          DOCKERHUB_PW: ${{secrets.DOCKERHUB_PW}}
          DOCKERHUB_UN: ${{secrets.DOCKERHUB_UN}}
          DOCKERHUB_URL: ${{secrets.DOCKERHUB_URL}}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: |
          python3 -m pip install numpy==1.19.2 PyGitHub==1.53 PyYAML==5.3.1 pytest==6.2.2
          pytest tests/test_functions.py -vv
  validate_update_relations:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Check update_relations.py
        id: checkUpdateReleations
        env:
          DEPLOY_BRANCH: ${{secrets.DEPLOY_BRANCH}}
          DOCKERHUB_ORG: ${{secrets.DOCKERHUB_ORG}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: |
          python3 -m pip install numpy==1.19.2 PyGitHub==1.53 PyYAML==5.3.1 pytest==6.2.2
          pytest tests/test_update_relations.py -vv
  validate_ci_latest_images:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Check scripts/ci_latest_images.py
        id: checkCILatestImages
        env:
          DEPLOY_BRANCH: ${{secrets.DEPLOY_BRANCH}}
          DOCKERHUB_ORG: ${{secrets.DOCKERHUB_ORG}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOCKERHUB_PW: ${{secrets.DOCKERHUB_PW}}
          DOCKERHUB_UN: ${{secrets.DOCKERHUB_UN}}
          DOCKERHUB_URL: ${{secrets.DOCKERHUB_URL}}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: |
          python3 -m pip install numpy==1.19.2 PyGitHub==1.53 PyYAML==5.3.1 pytest==6.2.2
          pytest tests/test_ci_latest_images.py -vv
  validate_ci_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Check scripts/ci_latest_images.py
        id: checkCILatestImages
        env:
          DEPLOY_BRANCH: ${{secrets.DEPLOY_BRANCH}}
          DOCKERHUB_ORG: ${{secrets.DOCKERHUB_ORG}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOCKERHUB_PW: ${{secrets.DOCKERHUB_PW}}
          DOCKERHUB_UN: ${{secrets.DOCKERHUB_UN}}
          DOCKERHUB_URL: ${{secrets.DOCKERHUB_URL}}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: |
          python3 -m pip install numpy==1.19.2 PyGitHub==1.53 PyYAML==5.3.1 pytest==6.2.2
          pytest tests/test_ci_image.py -vv
